apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../../base
images:
  - name: owlcms
    newName: owlcms-docker-containers.bintray.io/owlcms
    newTag: latest
  - name: publicresults
    newName: owlcms-docker-containers.bintray.io/publicresults
    newTag: latest  
resources:
- networkpolicies.yaml
- ingress.yaml
- services.yaml
commonLabels:
  environment: production
  
  
