apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  labels:
    app: owlcms
  name: owlcms-ingress
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    kubernetes.io/ingress.class: traefik
    ingress.kubernetes.io/ssl-redirect: 'false'
spec:
  tls:
    - hosts:
        - ${OFFICIALS}
      secretName: owlcms-ingress
  rules:
    - host: ${OFFICIALS}
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: owlcms-8080
                port:
                  number: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  labels:
    app: publicresults
  name: publicresults-ingress
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    kubernetes.io/ingress.class: traefik
    ingress.kubernetes.io/ssl-redirect: 'false'
spec:
  tls:
    - hosts:
        - ${RESULTS}
      secretName: publicresults-ingress
  rules:
    - host: ${RESULTS}
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: publicresults-8080
                port:
                  number: 8080
